### ISSUE TITLE
Support parceble

### ISSUE THREAD

**Issue by frakc** [bluelinelabs/LoganSquare#1]
Hello.
I am just currios if it can be not a serialisable, but parceble instead?
There is already a sweat library, which makes any object a parceble https://github.com/sockeqwe/ParcelablePlease  and I just wondering if you can extend your library... Probably I am too lazy. Still you library is great.

**Comment by Nilzor** [comment]
Why would you need this library to do that when one already exists?

**Comment by EricKuck** [comment]
Parcelable serialization doesn't really have anything to do with JSON. I agree with @Nilzor - if you want to generate Parcelables using annotation processors, why not use ParcelablePlease?
