### ISSUE TITLE
suggestion: when checking for getter/setting, check for is* and has* getter methods

### ISSUE THREAD

**Issue by kenkyee** [bluelinelabs/LoganSquare#101]
If I mark a field in a model like this:
````
    @JsonField(name="Control")
    private boolean isControl;
````

I have to add an unnecessary getIsControl method which isn't generated by android studio's getter/setter generator:
````
    public boolean isControl() {
        return isControl;
    }
    public boolean getIsControl() {
        return isControl;
    }

    public void setIsControl(boolean isControl) {
        this.isControl = isControl;
    }
````
or it complains:
Error:(26, 21) error: @JsonField annotation can only be used on private fields if both getter and setter are present.

**Comment by EricKuck** [comment]
Prefixing a boolean with is* was actually already supported. The issue was that your variable already had is*, which meant it didn't need to be prefixed with anything at all. I've added support for has* and no prefixes in v1.2.3.
