### ISSUE TITLE
Unable to compile with parent mapper in another module with 1.2.9

### ISSUE THREAD

**Issue by bluef** [bluelinelabs/LoganSquare#104]
JsonMapperLoaderImpl in 1.2.x is module specific, which make it impossible to compile JsonObject across modules, e.g. JsonObjectA extends JsonObjectB which in different module

1.1.0 works well

**Comment by EricKuck** [comment]
Would it be possible for you to create a sample project that demonstrates this issue? There's a few different ways you can do modules and I want to make sure I'm covering your use case in whatever fix we come up with.

**Comment by bluef** [comment]
for example we have module A which is basically full of basic class
```
package com.nice.common.data.json;

import com.bluelinelabs.logansquare.annotation.JsonField;
import com.bluelinelabs.logansquare.annotation.JsonObject;

@JsonObject
public class BaseResponse {
    @JsonField(name = "code")
    public int code;
}
```

and we have module B which is full of logic code and have module A as dependency
```
package com.nice.main.tagdetail.pojo;

import com.bluelinelabs.logansquare.annotation.JsonField;
import com.bluelinelabs.logansquare.annotation.JsonObject;
import com.common.data.json.BaseNextKeyList;
import com.common.data.json.BaseResponse;

import java.util.List;

@JsonObject
public class UserListPojo extends BaseResponse {
    @JsonField(name = "data")
    public UserListEntity data;

    @JsonObject
    public static class UserListEntity extends BaseNextKeyList {
        @JsonField(name = "users")
        public List<User> users;
    }
}
```

then we compile, we got the following error
```
/Users/bluef/Documents/code/nice_android.git/app/build/generated/source/apt/china/debug/com/nice/main/tagdetail/pojo/UserListPojo$UserListEntity$$JsonObjectMapper.java:19: Error: Can't find symbol
  private static JsonMapper<BaseNextKeyListPojo> parentObjectMapper = JsonMapperLoaderImpl.COM_NICE_COMMON_DATA_JSONPOJO_BASENEXTKEYLISTPOJO__JSONOBJECTMAPPER;
                                                                                          ^
  Symbol: Variables COM_NICE_COMMON_DATA_JSONPOJO_BASENEXTKEYLISTPOJO__JSONOBJECTMAPPER
  Position: Class JsonMapperLoaderImpl
```

so in the error above, the JsonMapperLoaderImpl mentioned is in moduleA, but the symbol COM_NICE_COMMON_DATA_JSONPOJO_BASENEXTKEYLISTPOJO__JSONOBJECTMAPPER we are looking for is in the JsonMapperLoaderImpl in moduleB which do have that symbol.

I've remove some app specificed code so the code above is just for demostration.

**Comment by mariotaku** [comment]
I can confirm this issue. 

LoganSquare compiler generates a JsonMapperLoaderImpl class for each module, which causes conflicts during build.

There's a simple & quick solution, that is generate a unique suffix for each JsonMapperLoaderImpl into a empty package, for example com.bluelinelabs.logansquare.impl.JsonMapperLoaderImpl_[md5], and load them all when initializing LoganSquare class.

**Comment by mariotaku** [comment]
@bluef Hi, I issued a pull request to this problem, could you try my patch and see whether it works?

**Comment by bluef** [comment]
@mariotaku I think that makes sense. Would you mind that show me how to apply your patch or compile with your fork?

**Comment by mariotaku** [comment]
@bluef Just quote those maven specified fields in build.gradle, like
````gradle

    bintray {
        user = 'bintray_username'
        key = 'bintray_api_key'
    }
````

**Comment by bluef** [comment]
@mariotaku Thanks. I've tried your patch and things work as a charm. Wish @EricKuck could merge your pull request. :)

**Comment by EricKuck** [comment]
This was fixed by removing the JsonMapperLoader completely. It's now working in v1.3.4.
