### ISSUE TITLE
Symbol not found "JsonToken.VALUE_NULL" in resulting `ModelName$$JsonObjectMapper` class

### ISSUE THREAD

**Issue by trevjonez** [bluelinelabs/LoganSquare#105]
The strings used to generate statements should use $T to ensure java poet can resolve and add the needed import correctly.

`"$L.getCurrentToken() == JsonToken.VALUE_NULL ? null : Boolean.valueOf($L.getValueAsBoolean())"`

should be 
`"$L.getCurrentToken() == $T.VALUE_NULL ? null : Boolean.valueOf($L.getValueAsBoolean())"`

passing in the additional `JsonToken.class` parameter for that $T representation to the `addStatement(...)` call.

Effected Files:
[processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/DoubleFieldType.java](https://github.com/bluelinelabs/LoganSquare/blob/master/processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/DoubleFieldType.java)
[processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/FloatFieldType.java](https://github.com/bluelinelabs/LoganSquare/blob/master/processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/FloatFieldType.java)
[processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/IntegerFieldType.java](https://github.com/bluelinelabs/LoganSquare/blob/master/processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/IntegerFieldType.java)
[processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/LongFieldType.java](https://github.com/bluelinelabs/LoganSquare/blob/master/processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/LongFieldType.java)
[processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/ByteFieldType.java](https://github.com/bluelinelabs/LoganSquare/blob/master/processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/ByteFieldType.java)
[processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/BooleanFieldType.java](https://github.com/bluelinelabs/LoganSquare/blob/master/processor/src/main/java/com/bluelinelabs/logansquare/processor/type/field/BooleanFieldType.java)

**Comment by EricKuck** [comment]
Merged into dev and will be included with the next release (v1.3.5). Thanks!
