### ISSUE TITLE
[NPE] Parent object mapper can be null

### ISSUE THREAD

**Issue by eirnym** [bluelinelabs/LoganSquare#113]
Current `LS` version (1.3.3) generates wrong order in `JsonMapperLoaderImpl` which doesn't mind about inheritance. So it can happen that parent load object is created later than child one.

```java
@JsonObject
public class Z {
  @JsonField
  public String a;
}

@JsonObject
public class A extends Z {
  @JsonField
  public String b;
}
```

which can generate following code (only actual parts only are shown):
```java
public class JsonMapperLoaderImpl implements JsonMapperLoader { 
public static final A A$$JsonObjectMapper  MY_PKG_A__JSONOBJECTMAPPER = A()
public static final Z Z$$JsonObjectMapper  MY_PKG_Z__JSONOBJECTMAPPER = Z()
...
}

public final class A$$JsonObjectMapper extends JsonMapper<LoadProfileResult> {
  private static final JsonMapper<JsonApiResult> parentObjectMapper = JsonMapperLoaderImpl. MY_PKG_Z__JSONOBJECTMAPPER;
...
}
```
At this point of execution, `parentObjectMapper` will be null and method throws `NullPointerException`
```java
  @Override
  public void parseField(LoadProfileResult instance, String fieldName, JsonParser jsonParser) throws IOException {
    if ("b".equals(fieldName)) {
      instance.b = jsonParser.getValueAsString(null);
    } else {
      parentObjectMapper.parseField(instance, fieldName, jsonParser);
    }
  }
```

**Comment by eirnym** [comment]
The possible solution is get parent mappers after putting them to the map in `JsonMapperLoaderImpl`.

**Comment by eirnym** [comment]
This happen when we have several root objects or deep hierarchy.

**Comment by eirnym** [comment]
#114 fixes this

**Comment by EricKuck** [comment]
Thanks for the PR @eirnym. I ended up deciding that the JsonMapperLoader stuff was just causing too many issues and scrapped the whole idea. v1.3.4 fixes this issue by removing the Loader completely.

**Comment by eirnym** [comment]
@EricKuck Thank you! this solution much better
