### ISSUE TITLE
Local field names should remove special characters except _UnderScore

### ISSUE THREAD

**Issue by mipreamble** [bluelinelabs/LoganSquare#115]
Local field names for a JsonField name "list-user" is causing a compile time error in generated classes.

Any special characters should be removed.

https://github.com/bluelinelabs/LoganSquare/blob/master/processor/src/main/java/com/bluelinelabs/logansquare/processor/type/collection/SingleParameterCollectionType.java#L50

**Comment by EricKuck** [comment]
This fix will be released as v1.3.5, most likely within the next few hours.

**Comment by mipreamble** [comment]
Thanks @EricKuck
