### ISSUE TITLE
How to deal with problem: the key is java keyword :"abstract" 

### ISSUE THREAD

**Issue by oubowu** [bluelinelabs/LoganSquare#126]
@JsonObject(fieldDetectionPolicy = JsonObject.FieldDetectionPolicy.NONPRIVATE_FIELDS_AND_ACCESSORS)
public class BaiduBaike {

    public String abstract;

}

**Comment by aurae** [comment]
Rename your field to something that isn't a Java keyword. If the JSON that you're consuming uses the string `"abstract"`, annotate your field with `@JsonField` and set its `name` property:

```java
@JsonObject(fieldDetectionPolicy = JsonObject.FieldDetectionPolicy.NONPRIVATE_FIELDS_AND_ACCESSORS)
public class BaiduBaike {
    @JsonField(name = "abstract")
    public String abstractValue;
}
```

**Comment by oubowu** [comment]
@aurae Thanks a lot!
