### ISSUE TITLE
LoganSquare can't serialize a collection of objects it knows how to serialize

### ISSUE THREAD

**Issue by kenkyee** [bluelinelabs/LoganSquare#128]
E.g., if you have
List<SomeObject> someobjects = ArrayList();

LoganSquare.serialize(someobjects)
Will throw an exception that Logansquare doesn't have an object mapper for ArrayList.

If it sees a collection, it should just serialize it as a JSON array...e.g.,
[ {obj1}, {obj2}, {obj3}... ]

**Comment by EricKuck** [comment]
public static <E> String serialize(List<E> list, Class<E> jsonObjectClass)`. It has to know what class you're serializing, as it doesn't use reflection.
