### ISSUE TITLE
LoganSquare has problems parsing ISO8601 dates?

### ISSUE THREAD

**Issue by kenkyee** [bluelinelabs/LoganSquare#129]
{
	"synced": "2016-12-14T21:32:50",
}

object model is:
@JsonObject
public class FileListResponse extends BaseResponse {
    @JsonField(name="synced")
    private Date lastSynced;
...
}

**Comment by EricKuck** [comment]
As the docs state, it has a default date formatter built in. If you want to use a different formatter, just add a type converter for it. The one that's built in is this format: `yyyy-MM-dd'T'HH:mm:ss.SSSZ`. 

https://github.com/bluelinelabs/LoganSquare/blob/master/docs/TypeConverters.md

**Comment by kenkyee** [comment]
Thanks, Eric.

In case anyone else hits this w/ a server API that isn't correct...do this:

````
public class ISO8601DateConverter extends DateTypeConverter {

    private DateFormat mDateFormat;

    public ISO8601DateConverter() {
        mDateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.getDefault());
    }

    public DateFormat getDateFormat() {
        return mDateFormat;
    }

}
````

And mark up your model's field like this:

    @JsonField(name="synced", typeConverter=SSISO8601DateConverter.class)
    private Date lastSynced;

**Comment by Zhuinden** [comment]
I would look into making this into a type converter  https://github.com/realm/realm-java/blob/14e0e0695851b57b24c89691f4197bd93bb4e7a8/realm/realm-library/src/main/java/io/realm/internal/android/ISO8601Utils.java
