### ISSUE TITLE
test failures in master

### ISSUE THREAD

**Issue by andaag** [bluelinelabs/LoganSquare#13]
There are several test failures in master

**Comment by andaag** [comment]
```
com.bluelinelabs.logansquare.processor.MultipleFieldNamesModelTest > generatedSource FAILED
    java.lang.AssertionError at MultipleFieldNamesModelTest.java:18

com.bluelinelabs.logansquare.processor.SimpleModelTest > generatedSource FAILED
    java.lang.AssertionError at SimpleModelTest.java:18

com.bluelinelabs.logansquare.processor.SimpleCollectionModelTest > generatedSource FAILED
    java.lang.AssertionError at SimpleCollectionModelTest.java:18

com.bluelinelabs.logansquare.processor.PrivateFieldModelTest > generatedSource FAILED
    java.lang.AssertionError at PrivateFieldModelTest.java:18

```

**Comment by EricKuck** [comment]
They're all passing for me. Any idea what the errors are exactly? Gradle should produce a .html file with actual stack traces.

**Comment by talklittle** [comment]
LoganSquare expects you to use Java 7. I got these errors too when using JDK 8.

**Comment by EricKuck** [comment]
I'll close this for now, since the tests do pass using Java 7. I'll circle back to Java 8 compatibility once I get a little more time. If you can post the html that gradle generates with all the errors, that would be really helpful.
