### ISSUE TITLE
Why LoganSquare faster than gson and Jackson ? 

### ISSUE THREAD

**Issue by muyiou** [bluelinelabs/LoganSquare#130]
LoganSquare just use Jackson's streaming API and apt to generate code,why faster than gson and Jackson?

**Comment by bunnyblue** [comment]
编译期间生成json解析嗲吗，gson之类用的反射

**Comment by muyiou** [comment]
@bunnyblue 那不用apt生成代码，直接用jackson不也一样？为什么会比Jackson快？

**Comment by EricKuck** [comment]
Jackson doesn't do compile-time code generation. It tries to figure it all out on the fly, and Java reflection is slow.

**Comment by muyiou** [comment]
@EricKuck  thank you for your answer
