### ISSUE TITLE
hello how can i use getter setter on this thing :(

### ISSUE THREAD

**Issue by Dj-jom2x** [bluelinelabs/LoganSquare#132]
import com.bluelinelabs.logansquare.annotation.JsonObject;

import java.util.ArrayList;
import java.util.Date;

/**
 * Created by Dj-joms2x on 1/20/2016.
 */

public class about_class
{

    class School
    {
        private String id;

        public String getId() { return this.id; }

        public void setId(String id) { this.id = id; }

        private String name;

        public String getName() { return this.name; }

        public void setName(String name) { this.name = name; }
    }

    class Concentration
    {
        private String id;

        public String getId() { return this.id; }

        public void setId(String id) { this.id = id; }

        private String name;

        public String getName() { return this.name; }

        public void setName(String name) { this.name = name; }
    }

    class Education
    {
        private School school;

        public School getSchool() { return this.school; }

        public void setSchool(School school) { this.school = school; }

        private String type;

        public String getType() { return this.type; }

        public void setType(String type) { this.type = type; }

        private ArrayList<Concentration> concentration;

        public ArrayList<Concentration> getConcentration() { return this.concentration; }

        public void setConcentration(ArrayList<Concentration> concentration) { this.concentration = concentration; }
    }

    class FavoriteAthlete
    {
        private String id;

        public String getId() { return this.id; }

        public void setId(String id) { this.id = id; }

        private String name;

        public String getName() { return this.name; }

        public void setName(String name) { this.name = name; }
    }

    class FavoriteTeam
    {
        private String id;

        public String getId() { return this.id; }

        public void setId(String id) { this.id = id; }

        private String name;

        public String getName() { return this.name; }

        public void setName(String name) { this.name = name; }
    }

    class Hometown
    {
        private String id;

        public String getId() { return this.id; }

        public void setId(String id) { this.id = id; }

        private String name;

        public String getName() { return this.name; }

        public void setName(String name) { this.name = name; }
    }

    class Location
    {
        private String id;

        public String getId() { return this.id; }

        public void setId(String id) { this.id = id; }

        private String name;

        public String getName() { return this.name; }

        public void setName(String name) { this.name = name; }
    }

    class Employer
    {
        private String id;

        public String getId() { return this.id; }

        public void setId(String id) { this.id = id; }

        private String name;

        public String getName() { return this.name; }

        public void setName(String name) { this.name = name; }
    }

    class Position
    {
        private String id;

        public String getId() { return this.id; }

        public void setId(String id) { this.id = id; }

        private String name;

        public String getName() { return this.name; }

        public void setName(String name) { this.name = name; }
    }

    class Work
    {
        private String description;

        public String getDescription() { return this.description; }

        public void setDescription(String description) { this.description = description; }

        private Employer employer;

        public Employer getEmployer() { return this.employer; }

        public void setEmployer(Employer employer) { this.employer = employer; }

        private Position position;

        public Position getPosition() { return this.position; }

        public void setPosition(Position position) { this.position = position; }

        private String start_date;

        public String getStartDate() { return this.start_date; }

        public void setStartDate(String start_date) { this.start_date = start_date; }
    }

    private String id;

    public String getId() { return this.id; }

    public void setId(String id) { this.id = id; }

    private String birthday;

    public String getBirthday() { return this.birthday; }

    public void setBirthday(String birthday) { this.birthday = birthday; }

    private ArrayList<Education> education;

    public ArrayList<Education> getEducation() { return this.education; }

    public void setEducation(ArrayList<Education> education) { this.education = education; }

    private ArrayList<FavoriteAthlete> favorite_athletes;

    public ArrayList<FavoriteAthlete> getFavoriteAthletes() { return this.favorite_athletes; }

    public void setFavoriteAthletes(ArrayList<FavoriteAthlete> favorite_athletes) { this.favorite_athletes = favorite_athletes; }

    private ArrayList<FavoriteTeam> favorite_teams;

    public ArrayList<FavoriteTeam> getFavoriteTeams() { return this.favorite_teams; }

    public void setFavoriteTeams(ArrayList<FavoriteTeam> favorite_teams) { this.favorite_teams = favorite_teams; }

    private String first_name;

    public String getFirstName() { return this.first_name; }

    public void setFirstName(String first_name) { this.first_name = first_name; }

    private String gender;

    public String getGender() { return this.gender; }

    public void setGender(String gender) { this.gender = gender; }

    private Hometown hometown;

    public Hometown getHometown() { return this.hometown; }

    public void setHometown(Hometown hometown) { this.hometown = hometown; }

    private ArrayList<String> interested_in;

    public ArrayList<String> getInterestedIn() { return this.interested_in; }

    public void setInterestedIn(ArrayList<String> interested_in) { this.interested_in = interested_in; }

    private String last_name;

    public String getLastName() { return this.last_name; }

    public void setLastName(String last_name) { this.last_name = last_name; }

    private String link;

    public String getLink() { return this.link; }

    public void setLink(String link) { this.link = link; }

    private Location location;

    public Location getLocation() { return this.location; }

    public void setLocation(Location location) { this.location = location; }

    private String locale;

    public String getLocale() { return this.locale; }

    public void setLocale(String locale) { this.locale = locale; }

    private String middle_name;

    public String getMiddleName() { return this.middle_name; }

    public void setMiddleName(String middle_name) { this.middle_name = middle_name; }

    private String name;

    public String getName() { return this.name; }

    public void setName(String name) { this.name = name; }

    private int timezone;

    public int getTimezone() { return this.timezone; }

    public void setTimezone(int timezone) { this.timezone = timezone; }

    private Date updated_time;

    public Date getUpdatedTime() { return this.updated_time; }

    public void setUpdatedTime(Date updated_time) { this.updated_time = updated_time; }

    private boolean verified;

    public boolean getVerified() { return this.verified; }

    public void setVerified(boolean verified) { this.verified = verified; }

    private String website;

    public String getWebsite() { return this.website; }

    public void setWebsite(String website) { this.website = website; }

    private ArrayList<Work> work;

    public ArrayList<Work> getWork() { return this.work; }

    public void setWork(ArrayList<Work> work) { this.work = work; }
}

// is this posible in logan square? .. because i have no idea how to do your modeling part :( i only know gson ..

 public void onSuccess(int statusCode, Header[] headers, JSONObject response) {

                String jsonString = response.toString();
                GsonBuilder gsonb = new GsonBuilder();
                Gson gson = gsonb.create();
                about_class data = gson.fromJson(jsonString, about_class.class);
                Log.e("Name",data.getName());

   }

**Comment by EricKuck** [comment]
Just annotate the fields as `JsonField`s and the getters and setters will be picked up automatically.

**Comment by goncalossilva** [comment]
What if you don't have access to the fields (eg. a subclass of a library class you want to parse)? Any suggestions to handle this case?

**Comment by EricKuck** [comment]
Sorry, it's not going to work for that. It uses annotation processing, so
you have to be able to annotate.

**Comment by goncalossilva** [comment]
Getters, setters and constructor parameters can be annotated on the subclass. What am I missing?

**Comment by EricKuck** [comment]
Right now fields have to be annotated, but that's a good idea for a future
update.

**Comment by goncalossilva** [comment]
Alright, thanks for the discussion. Looking forward to it 😄
