### ISSUE TITLE
Generic IntBasedTypeConverter that converts ints to enums

### ISSUE THREAD

**Issue by rockstardev** [bluelinelabs/LoganSquare#136]
I'm probably missing something - but couldn't find something generic that would allow me to register my enums for handling by library.

Only thing I've found is this page that shows how to create converter for each enum in your project:
https://github.com/bluelinelabs/LoganSquare/blob/master/docs/TypeConverters.md

If generic enum is already part of the library, let me know, if not - here is one I wrote for anybody who stumbles on this page:

```
import com.bluelinelabs.logansquare.typeconverters.IntBasedTypeConverter;

public class GenericIntBasedTypeConverter<T extends Enum<T>> extends IntBasedTypeConverter<T> {
    private Class<T> mClass;

    public GenericIntBasedTypeConverter(Class<T> cls) {
        mClass = cls;
    }

    @Override
    public T getFromInt(int i) {
        for (T c : mClass.getEnumConstants()) {
            if (c.ordinal() == i)
                return c;
        }

        return null;
    }

    @Override
    public int convertToInt(T enumValue) {
        return enumValue.ordinal();
    }
}
```

And then you can register your enums:

```
LoganSquare.registerTypeConverter(MyEnum1.class, new GenericIntBasedTypeConverter<>(MyEnum1.class));
LoganSquare.registerTypeConverter(MyEnum2.class, new GenericIntBasedTypeConverter<>(MyEnum2.class));
LoganSquare.registerTypeConverter(MyEnum3.class, new GenericIntBasedTypeConverter<>(MyEnum3.class));
```

**Comment by lepipele** [comment]
And one important notice - this obviously doesn't work with with enums that have custom integer values - if somebody handles this, please post here.

**Comment by aurae** [comment]
Well, there is [EnumValueTypeConverter](https://github.com/bluelinelabs/LoganSquare/blob/master/core/src/main/java/com/bluelinelabs/logansquare/typeconverters/EnumValueTypeConverter.java), which operates on strings though.

**Comment by lepipele** [comment]
@aurae Yeah - I saw that one, but I needed something that works on integers for web service that returns {MyEnum:1} instead of {MyEnum:"value1"}
