### ISSUE TITLE
How to parse a weird JSON structure?

### ISSUE THREAD

**Issue by ppamorim** [bluelinelabs/LoganSquare#138]
Well, I have a JSON that have a weird structure, I cannot parse this correctly:

```json
[
  {
    "object": {
    }
  },
  {
    "object": {
    }
  }
]
```
This library could use the annotation `@JsonObject` to do it, like `@JsonObject(find="object")`. What do you think about? Anyone can help me?

**Comment by ppamorim** [comment]
Here is my workaround:

```java
JSONArray jsonArray = new JSONArray(json);
int size = jsonArray.length();
ArrayList<Object> jsonObjects = new ArrayList<>(size);
for(int i = 0; i < size; i++) {
  jsonObjects.add(jsonArray.getJSONObject(i).get("object"));
}
```

**Comment by EricKuck** [comment]
You should be able to parse that as an array of objects that have an "object" field. What was the issue you had exactly?
