### ISSUE TITLE
How to add to a non-Android library

### ISSUE THREAD

**Issue by jazzgil** [bluelinelabs/LoganSquare#140]
Hi, 
I'm using a shared library for a project which has both an Android app and an App Engine backend. The library is included in both targets: app and backend, to enable me to share some common structures and utilities. This is also the place I would like to put my JSON classes, so both can share them. However, when trying to add the android-apt plugin to the common library build.gradle, it naturally shouts that it requires the android plugin or the android-library plugin. I cannot convert my library to an android-library as it is also included in the App Engine module.

Alternatively, how can LoganSquare be used in an AppEngine module? If that can be solved, I could just duplicate the bean definitions for both android and AppEngine environments.

Any workaround comes to mind? Is there a way to replace the android-apt with something else?

Thanks

**Comment by aurae** [comment]
You should be able to use the [Java apt plugin](https://plugins.gradle.org/plugin/net.ltgt.apt) instead.

**Comment by jazzgil** [comment]
@aurae, you are my hero!  Thanks.
