### ISSUE TITLE
Dynamically ignore JsonField

### ISSUE THREAD

**Issue by ntimesc** [bluelinelabs/LoganSquare#151]
Is there any way to ignore jsonfield dynamically. 

Scenario is 

@JsonObject
public class UserRequest  {

```
@JsonField

private String userId;

@JsonField
private String organizationId;
```

   @JsonField
    private String operationCode;

}

for some of the requests i need *_operationCode *_ and for some request i want to ignore it , this is how i can reuse the model.

**Comment by mannodermaus** [comment]
LoganSquare won't break if there is a `@JsonField` that's not part of the actual model. Instead, that field will simply not be initialized. For those responses that don't contain the `operationCode`, that field is null. You could:

1) Annotate the accessor for that field with `@Nullable`
2) Have the accessor for that field return `Optional<String>` instead
3) Remove the field from your general model class, sub-class it, add the field into the sub-class and use that for the responses that actually contain the `operationCode`

**Comment by EricKuck** [comment]
Great answer @aurae. If the operationCode is only needed for some requests, that sounds like a great reason to make another model, which is a subclass of your base. But if for whatever reason you want to stick with one model, nothing will break if operationCode is null.
