### ISSUE TITLE
How to parse array of arrays?

### ISSUE THREAD

**Issue by MGasztold** [bluelinelabs/LoganSquare#162]
How should i handle JSON object field being an array like this?

```
"vertices": [  [3413.33,3728.0], [1990.61,3444.67],  ...   ]  
```

I have tried the following:

```
@JsonField(name = "vertices")
public List<List<Double>> vertices_;
```

and

```
@JsonField(name = "vertices")
public List<Double[]> vertices_;
```

but the result is always an array with elements that are null.

<img width="284" alt="screen shot 2016-05-11 at 17 19 47" src="https://cloud.githubusercontent.com/assets/11412357/15186268/a745df92-179c-11e6-9e45-5fd8279bd096.png"> 
The picture above shows the state of the `vertices_` array at the begining of 

```
@OnJsonParseComplete
void onParseComplete() {...}
```

method. Please help.

**Comment by mannodermaus** [comment]
Using the second approach you mentioned, I'm able to get LoganSquare to parse the information correctly using version `1.3.7`:

``` java
@JsonObject
public class Whatever {
    @JsonField(name = "vertices")
    List<Double[]> vertices;
}
```

``` json

{  
   "list":[  
      {
         "vertices":[[2.4, 1.3, 5.6], [9.6, 8.4, 3.5]]
      },
      {
         "vertices":[[2.4, 1.3, 5.6], [9.6, 8.4, 3.5]]
      },
      [...]
   ]
}
```

![bildschirmfoto 2016-05-11 um 17 47 46](https://cloud.githubusercontent.com/assets/3897705/15187258/b929d9bc-17a0-11e6-9c92-d6542760cf38.png)

What version are you using? Does LoganSquare pick up the rest of your model correctly? It's weird how it seems to notice that you have 48 elements in your list, yet all of them are `null`.

**Comment by MGasztold** [comment]
I have found that I had other bug. The approach of 

```
 @JsonField(name = "vertices")
    List<Double[]> vertices;
```

works well. Thanks !
