### ISSUE TITLE
Problem code generation

### ISSUE THREAD

**Issue by mgpx** [bluelinelabs/LoganSquare#163]
I am having problem when compiling the code, I have a class (Struct1) there is a list of Struct2 ... And these structures are in other packages within the application ...

com.example.test.app is my package

I have classes in packages internels ...

WebService.StructsExample.Struct1
WebService.StructsExample.Struct2

Struct one

```
package com.example.test.app.WebService.StructsExample;
@JsonObject
public class Struct1{
    @JsonField
    public String field1;
    @JsonField
    public String field2;
    @JsonField
    public List<Struct2> itens;
}
```

and Struct two 

```
package com.example.test.app.WebService.StructsExample;
@JsonObject
public class Struct2{
    @JsonField
    public Long id;
    @JsonField
    public Double value;
}
```

during compilation generates the following code

```
package com.example.test.app.WebService.StructsExample;
import..
import com.example.test.app.WebService; // package invalid // this line is not necessary

public final class Struct1$$JsonObjectMapper extends JsonMapper<Struct1> {

private static final JsonMapper<WebService.StructsExample.Struct1> COM_EXAMPLE_TEST_APP_WEBSERVICE_STRUCTSEXAMPLE_STRUCT1__JSONOBJECTMAPPER = LoganSquare.mapperFor(WebService.StructsExample.Struct1.class);
//"WebService.StructsExample.Struct1" is invalid
//it should be
//private static final JsonMapper<Struct1> COM_EXAMPLE_TEST_APP_WEBSERVICE_STRUCTSEXAMPLE_STRUCT1__JSONOBJECTMAPPER = LoganSquare.mapperFor(Struct1.class);
}

@Override
  public void parseField(Struct1 instance, String fieldName, JsonParser jsonParser) throws IOException{
     //It has the same problem in items inside
}

@Override
  public void serialize(Struct1 object, JsonGenerator jsonGenerator, boolean writeStartAndEnd) throws IOException {
     //It has the same problem in items inside
}
```

If anyone know how I can solve this would be very grateful.

PS: Sorry my English is not very good, newly I entered the github, so forgive me if I did something wrong!

**Comment by trevjonez** [comment]
It looks like you have either capital letters in your package naming which i believe is illegal and is tripping up the javapoet causing it to think you have three levels of inner classes.

Start with fixing your package naming and see if that resolves the issue.

**Comment by mgpx** [comment]
Thank you, changed to lowercase and it worked.
