### ISSUE TITLE
Feature Request: Native support on annotationProcessor Gradle Task 

### ISSUE THREAD

**Issue by peterbetos** [bluelinelabs/LoganSquare#165]
Hi bluelinelabs - If you can have this compatible with annotationProcessor as well aside from the apt plugin, it can reduce the dependency on additional 3rd party plugin for the annotation processing natively supported on Android N.

Here's the setup to validate the support:
parent build.gradle should be using 
`classpath 'com.android.tools.build:gradle:2.2.0-alpha1'`

The following line is removed on the application build.gradle
`apply plugin: 'com.neenbedankt.android-apt'`

Thanks.

**Comment by mannodermaus** [comment]
The `annotationProcessor` configuration is compatible with the libraries you used to pull in via `android-apt` by default and without any required additional work from our side. So, if you like, you can simply change your project to using that configuration, enable Jack, and you're good to go!

**Comment by peterbetos** [comment]
Thanks. I'll check and see if there won't be nullified instances. I've reported on Butterknife that the instances on their end are null when using annotationProcessor.

**Comment by mannodermaus** [comment]
Interesting... I conducted a small example project earlier, just to verify that it still works with the latest plugin version, and it did. Make sure you're up to `2.2.0-alpha3` though, maybe that was the issue with ButterKnife?

**Comment by trevjonez** [comment]
You can track the progress of the JACK compiler annotation processor support in the [AOSP issue tracker #204065.](https://code.google.com/p/android/issues/detail?id=204065)

**Comment by peterbetos** [comment]
Thanks. The new alpha version did it ;)
Edit. Still crashes. We can close this while Butterknife still has issues. Thanks.

**Comment by peterbetos** [comment]
The new 'com.android.tools.build:gradle:2.2.0-alpha6' addresses the issue. We can close this. Thanks.
