### ISSUE TITLE
Boxed variables not parsed

### ISSUE THREAD

**Issue by pavlospt** [bluelinelabs/LoganSquare#169]
Hello.

I have seen on your documentation that LoganSquare supports `Boxed` variable types. 

Although i have tried parsing Integers and Booleans but they seem to be defaulting to null and I can not find a proper reason for it.

``` java
@JsonField(name="some_variable_name")
private Integer someVariableName;
```

Is there something that I can do to find out what is going wrong?

**Comment by mannodermaus** [comment]
Boxed types are definitely supported in LoganSquare. Please ensure that your apt setup is correct, the `$$JsonObjectMapper` class is generated for your model and the mapped field name matches the JSON input fed into `LoganSquare#parse`. In case of special characters in your JSON fields, maybe it's an encoding issue?

Minimal example for boxed type support:

``` java
SomeThing.java:

@JsonObject
public class SomeThing {

    @JsonField(name = "primitive")
    int primitive;

    @JsonField(name = "boxed")
    Integer boxed;
}
```

``` java
SomeThingTest.java:

public class SomeThingTest {

    public static void main(String[] args) throws Exception {
        SomeThing thing = LoganSquare.parse("{\"primitive\": 1, \"boxed\": 2}", SomeThing.class);
        assert thing.primitive == 1;
        assert thing.boxed == 2;
    }
}
```

**Comment by pavlospt** [comment]
@aurae Actually i am using your Library to parse them through Retrofit and it just does not seem to work. All $$JsonMapper files are correctly generated but when trying to retrieve the value it is null.

**Comment by mannodermaus** [comment]
That's very weird. Again, using a simple example, I can parse boxed values into the model class without any hassle. Are you able to share the data you are consuming from the API, and more of your setup?

**Comment by pavlospt** [comment]
After some investigation, it seems that the problem was caused because of some not Annotated model that was related to the one containing the boxed values. It seemed very strange to me that there was no obvious error about this. Moreover I got exceptions for non-existent Mappers, on models that were fully Annotated.
