### ISSUE TITLE
How do I know what class is corrupted?

### ISSUE THREAD

**Issue by dmitrikudrenko** [bluelinelabs/LoganSquare#174]
I use kotlin and with compilation I receive that error

```
Error:@JsonField annotation can only be used on private fields if both getter and setter are present.
```

I haven't private fields. All my fields are public by default. How can I know what class can't be proccessed?

**Comment by LouisCAD** [comment]
Do you have any setter or getter in your model classes?

**Comment by dmitrikudrenko** [comment]
Actually no. But kotlin compiler creates getters and setters

**Comment by LouisCAD** [comment]
Can you show us how your models look? (feel free to create a sample version, using the same logic as your models)

**Comment by mannodermaus** [comment]
The annotation processor gives more information on the file and location where it encountered an invalid declaration. Can you check if there's more output below the line you quoted? You may also want to run Gradle with the `--stacktrace` or `--info` flags in order to have it show up.

An example:

``` java
@JsonObject
public class TestModel {

    @JsonField(name = "field")
    private int someField;
}

20:50:47: Executing external task 'build'...
/the/location/to/the/TestModel.java:10: error: @JsonField annotation can only be used on private fields if both getter and setter are present.
    private int someField;
                ^
1 error
:compileJava FAILED
```

**Comment by dmitrikudrenko** [comment]
Well, the problem was in fields with names started on 'is' (for example, isEnabled). I renamed it to 'enabled' and used @JsonField(names = arrayOf("isEnabled")). That error is viewed in https://github.com/bluelinelabs/LoganSquare/issues/101

**Comment by semenoh** [comment]
Have the same error but have no idea what's wrong `--stacktrace` and `--info` does not provide any additional info. How can I get any details on what class what field ?
Thanks
