### ISSUE TITLE
Support for exclusive field serialization

### ISSUE THREAD

**Issue by Nilzor** [bluelinelabs/LoganSquare#2]
The default behaviour now is obviously inclusive - you have to annotate each field with  `@JsonField`. Would it be possible to say that you should serialize *every* field in this class with for instance an annotation variable? E.g. `JsonObject(exclusive=true)`. Then you could opt out fields instead of opt in, with for instance `@JsonIgnore` or the `transient` keyword as native Java serialization does (Naming of annotations does not matter for me)

**Comment by pardom** [comment]
+1

**Comment by EricKuck** [comment]
I've considered doing something like this, but it seems more error-prone. There's a reason StackOverflow is flooded with people asking why things don't parse correctly in GSON or Jackson. I have a feeling people will throw a @JsonObject annotation at the top of their class, then get confused why it doesn't do everything exactly the way they want it (ex: field naming, ignoring certain properties, and parsing/serializing unsupported types). Probably 90% of the people who find an "issue" with GSON or Jackson actually just don't understand what they're supposed to be doing.

That being said, if this gets enough +1's, I'll add this. Instead of exclusive=true, I'll probably add an enum for what gets parsed/serialized, which will have the options of ANNOTATIONS_ONLY, ALL_FIELDS, ALL_FIELDS_AND_ACCESSORS or something like that.

**Comment by pardom** [comment]
I could see this as a "power user" feature that isn't advertised, but is well documented. The processor could throw warnings when @JsonField isn't used and other requirements aren't fulfilled.

**Comment by markrietveld** [comment]
+1 on some sort of auto-include behavior. It would make switching from another parser much easier. Especially for big apps with lots of existing model objects

**Comment by hzsweers** [comment]
+1 from me as well

**Comment by IamJAX** [comment]
+1 from me

**Comment by jenzz** [comment]
:+1:

**Comment by EricKuck** [comment]
This hasn't been documented or released to JCenter yet, but commit 41572aa599ec6deba268b3fa3928c1453d7c3b73 adds two new optional parameters to `@JsonObject`. 

The first is `fieldDetectionPolicy`, which takes an enum with options for `ANNOTATIONS_ONLY`, `NONPRIVATE_FIELDS`, and `NONPRIVATE_FIELDS_AND_ACCESSORS`. The ANNOTATIONS_ONLY options is the default, which is to only parse and serialize fields that have been annotated as `@JsonField`s. The `NONPRIVATE_FIELDS` option will parse and serialize all public or package-local fields, unless they've been annotated with `@JsonIgnore`. The `NONPRIVATE_FIELDS_AND_ACCESSORS` will parse and serialize all the same fields as `NONPRIVATE_FIELDS`, plus any fields that have public or package-local getters and setters.

The second field is `fieldNamingPolicy`, which handles how fields are expected to be named in the JSON. This is also an enum, with options for `FIELD_NAME` and `LOWER_CASE_WITH_UNDERSCORES`. The `FIELD_NAME` options is the default, and it will assume that your JSON has the same field names as your Java variables, unless they're annotated with `@JsonObject(name = "...")`. The `LOWER_CASE_WITH_UNDERSCORES` option will assume that your JSON has the same field names as your java variables, except in lower case with underscore format (again, unless annotated with `@JsonObject(name = "...")`.

How do these changes look? Are there any other field naming policies that might be useful? 

If you'd like to get this running before it's on JCenter, run `./gradlew publishToMavenLocal` on the root of the library source to get it in your local Maven repo. After that, you can use it in your own apps by changing the 1.0.1 versions to 1.0.2 on both the compiler and the runtime dependencies in your build.gradle file.

**Comment by hzsweers** [comment]
@EricKuck that seems perfect, and impressive given the time span you did this in. As for the field naming conventions, it might be simplest to just match what [Gson does](http://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/FieldNamingPolicy.html), including using the same names to make it easier for migrating developers and consistency.

> * `IDENTITY`
  * Using this naming policy with Gson will ensure that the field name is unchanged.
* `LOWER_CASE_WITH_DASHES` 
  * Using this naming policy with Gson will modify the Java Field name from its camel cased form to a lower case field name where each word is separated by a dash (-).
* `LOWER_CASE_WITH_UNDERSCORES` 
  * Using this naming policy with Gson will modify the Java Field name from its camel cased form to a lower case field name where each word is separated by an underscore (_).
* `UPPER_CAMEL_CASE` 
  * Using this naming policy with Gson will ensure that the first "letter" of the Java field name is capitalized when serialized to its JSON form.
* `UPPER_CAMEL_CASE_WITH_SPACES` 
  * Using this naming policy with Gson will ensure that the first "letter" of the Java field name is capitalized when serialized to its JSON form and the words will be separated by a space.

**Comment by EricKuck** [comment]
I considered doing what GSON does, but all of these seem unnecessary except for IDENTITY and LOWER_CASE_WITH_UNDERSCORES. Do any real-life APIs expect lower case with dashes, upper camel case, or even more unlikely, upper camel case with spaces? Unless there's a real reason for something I'd like to keep this library as simple as possible.

**Comment by EricKuck** [comment]
The library's been updated on JCenter. It's now 1.0.3 and includes the changes mentioned above. Hope that satisfies everyone's needs. Documentation will be added to the README.md file later tonight.

**Comment by jenzz** [comment]
Wow. Thanks for the prompt implementation @EricKuck :+1:
