### ISSUE TITLE
Generated JsonObjectMapper always use setters if setter exists

### ISSUE THREAD

**Issue by september669** [bluelinelabs/LoganSquare#202]
For example:

@JsonObject
public final class Foo
{
    @NonNull
    @JsonField(name = "camera_model")
    public String cameraModel;

    public void setCameraModel(@NonNull String cameraModel){
        this.cameraModel = cameraModel;
    }

}

And in Foo$$JsonObjectMapper:

  @Override
  public void parseField(CameraDeviceHardware instance, String fieldName, JsonParser jsonParser) throws IOException {
     if ("camera_model".equals(fieldName)) {
         instance.**setCameraModel**(jsonParser.getValueAsString(null));
     }
    ..
  }

And only if setter not exists Mapper uses direct access to field.
Is it correct?

**Comment by mannodermaus** [comment]
Yes

**Comment by september669** [comment]
thx
