### ISSUE TITLE
Add support for nested collection types

### ISSUE THREAD

**Issue by markrietveld** [bluelinelabs/LoganSquare#21]
This may be similar to https://github.com/bluelinelabs/LoganSquare/issues/11. Feel free to close this and only keep the other one if that makes sense

The specific case I'm trying to get solved is:
```java
public Map<String, List<MyObject>> myObjectsById
```

In  `parseField()`, this currently turns into (with compiler error "Cannot select from parameterized type")
```java
map.put(key, LoganSquare.typeConverterFor(java.util.List<MyObject>.class).parse(jsonParser));
```

This would work instead:
```java
map.put(key, LoganSquare.mapperFor(MyObject.class).parseList(jsonParser));
```

**Comment by EricKuck** [comment]
Making this work is going to take a rewrite of the way annotations are processed and classes are generated, so it might take a few days to get it done, but I definitely see the need for this to work. Thanks for submitting this.

**Comment by EricKuck** [comment]
Support for nested collections is now live on JCenter and Maven Central in version 1.0.6.
