### ISSUE TITLE
Boon or LoganSquare

### ISSUE THREAD

**Issue by shism2** [bluelinelabs/LoganSquare#22]
Is Boon or LoganSquare faster?

**Comment by hzsweers** [comment]
Pretty sure this isn't an "issue".

**Comment by EricKuck** [comment]
My guess is that LoganSquare is faster, but considering Boon's documents proudly say 

> The goal of Boon was never to be a small jar file that could get used on Android.
>
>(I actually hate Android and am a big iOS/OSX guy so... if it happens it will not be because I need it personally. It will be because someone else wants it and makes it happen. I had 5 Android devices. NOT. A. FAN. AT. ALL. )

I don't think it's worth bothering to compare them.
