### ISSUE TITLE
Support for generic classes

### ISSUE THREAD

**Issue by WoogieNoogie** [bluelinelabs/LoganSquare#24]
The majority of our JSON objects in our API responses are wrapped inside of a base object (meta/results), so we have a generic class to pass back results of any type. I've found the JsonObject annotation can't be used on generics. Any chance this can be supported at some point?

**Comment by EricKuck** [comment]
Without some pretty crazy tricks and a bunch of reflection, I don't see a way to add support for generic classes, as this library generates all the code at compile-time and Java generics are determined at runtime.

Happen to have any ideas on how this could be done?

**Comment by EricKuck** [comment]
Looking through the issue tracker on other (unrelated) projects that generate code, I'm thinking this isn't going to be possible without creating concrete versions of your wrapper class for every type you can parse/serialize from your API. 

I'd love for someone to prove me wrong!

**Comment by WoogieNoogie** [comment]
While the class technically is generic, we still know that it's only going to be one of the classes annotated with @JsonObject. I'm wondering if that can be used here? Or maybe some new annotation to specify which classes are allowed?

I completely get what you're saying. Maybe there is some tweaking I can do on our generic class as well to allow it in, or maybe I can take a look in the LoganSquare code to see if I have any ideas.

**Comment by EricKuck** [comment]
I might have a good idea for this. We have some hard deadlines coming up on some of our projects, but I'll see if I can get something proofed out in the next few days. Don't lose hope :)

Just FYI though, any possible solution to this is going to require using Java reflection, which is going to be inherently slower (although this applies equally to any JSON parsing library, including GSON and Jackson Databind). I *think* I have a good solution for getting around the reflection requirement on parsing, but I don't think there's going to be a workaround for serializing. Even with the optimal solution, you're going to get better performance by creating concrete wrapper classes for each possible type they could hold. I guess it's a tradeoff between writing a bunch of semi-useless code and performance.

**Comment by WoogieNoogie** [comment]
I appreciate you taking a look!

**Comment by R4md4c** [comment]
Did anyone please, find a workaround for using Generic classes with LoganSquare ?

I'm having a paged response and I don't want to write the same fields for different types of classes.

I want to implement something like this 
```
@JsonObject(fieldNamingPolicy = JsonObject.FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
public class PagedResponse<T extends MyInterface> {
    @JsonField
    int page;
    @JsonField
    int total;
    @JsonField
    int recordsPerPage;

    @JsonField
    List<T> records;
}
```

I would appreciate any suggestions about this matter.

**Comment by EricKuck** [comment]
As explained here: #96, this is now supported in the latest versions of LoganSquare. Sorry it took so long!
