### ISSUE TITLE
Wrapped objects

### ISSUE THREAD

**Issue by bleeding182** [bluelinelabs/LoganSquare#25]
I've already seen the generics issue #24 , this one is a little similar

I get a wrappen object

    { foo : { bar : "" , bar2 : ""}}
The same wrapped format for lists of this object

    [ {foo : { bar : "" , bar2 : ""}}, {foo : { bar : "" , bar2 : ""}}]

It would be nice to have an option to enable the removal of those wrapping elements, e.g. boolean flag defaults to false, if enabled it will just skip the wrapping element completely.

    _parse(JsonParser jsonParser) throws IOException {
        // .....
        if (jsonParser.getCurrentToken() != JsonToken.START_OBJECT) {
            jsonParser.skipChildren();
            return null;
        }
        // e.g. just add the following lines, not tested
        jsonParser.nextToken();
        while(jsonParser.getCurrentToken() != JsonToken.START_OBJECT )
            jsonParser.nextToken();
        // .....
    }

**Comment by EricKuck** [comment]
This kind of seems like the the responsibility of the consumer, not the JSON parser to me. How would the library know which objects to discard?

**Comment by bleeding182** [comment]
I see 2 possibilities:

- Provide some method to overwrite, called prior to parsind, so one could do it oneself

or
- Add some Property and / or annotation. Global on e.g LoganSquare.objectsAreWrapped(true), or in the annotation, and if set the generated code has the additional lines e.g. @JsonObject(wrappedObject = true)
One could even set the name, for which object to look for

Now I don't know to how many people this would be an issue for, albeit a hook prior to parsing would probably be nice.

kind regards

**Comment by EricKuck** [comment]
I'm just not seeing how the parser could possibly know what "wrapped" means for every single type of wrapper object out there without adding lots of cruft to the annotations. And even if it did, this would be a breaking change, as the parse methods would have to change from

`public static <E> E parse(String jsonString, Class<E> jsonObjectClass)`

to

`public static <E> YourWrapper<E> parse(String jsonString, Class<E> jsonObjectClass)`

To me this sounds like a huge amount of work for very little reward. Unwrapping objects still very much seems to be the responsibility of the consumer of this library, not the library itself. I'm sure people who receive wrapped objects from their APIs could write a 5 line unwrapping helper method that would do this for them very easily.
