### ISSUE TITLE
@JsonObject should be enough, no need to annotate each field with @JsonField

### ISSUE THREAD

**Issue by stephanenicolas** [bluelinelabs/LoganSquare#35]
Compared to Jackson, this is the main trouble with LoganSquare. 

An annotation processor can be triggered by the `@JsonObject` annotation but it should then look for all fields, annotated or not and generate code for those fields. We should then add a `@JsonIgnore` annotation to be able to filter out a few fields.

If we do so, `@JsonField` can still be used, for instance to give a special name to json entry for a field.

**Comment by EricKuck** [comment]
It already works this way. Please see https://github.com/bluelinelabs/LoganSquare/blob/master/docs/Models.md. The last two options do what you describe.

**Comment by stephanenicolas** [comment]
Are you sure @EricKuck , that's not what I experienced yesterday evening. I had to annotate each field.

And is there a `@JsonIgnore` annotation in LoganSquare ?

**Comment by EricKuck** [comment]
Yes, I'm sure. Please read the docs. They tell you exactly how to make this work and even specifically call out the `@JsonIgnore` annotation. You have to use the `fieldDetectionPolicy` parameter in the `@JsonObject` annotation.
