### ISSUE TITLE
NullPointerException with JsonField LinkedHashMap

### ISSUE THREAD

**Issue by dtogias** [bluelinelabs/LoganSquare#37]
Using a LinkedHashMap<String, Integer> does not work.
In BenchmarkDemo Response.java class add the following line

```
@JsonField
public LinkedHashMap<String, Integer> test;
```

**Comment by EricKuck** [comment]
It shouldn't throw a NPE, but the "Supported Data Types" doc does say that HashMap is the only supported concrete Map class. Probably wouldn't be all that hard to add support for other types, like LinkedHashMap or TreeMap though. Mind sharing the use case for requiring a LinkedHashMap vs. just using the Map interface?

**Comment by EricKuck** [comment]
Support for this has been added in 4ff9dd1133b70bffcf3b83dbf64d8a00e755d91b. This change will go out to JCenter and Maven Central with the next update (within the next week or so).

**Comment by dtogias** [comment]
@EricKuck There was no obvious/concrete reason for using a LinkedHashMap, so i changed it to a HashMap. 
I reported the crash since the documentation was not clear. Thank you for the fast reply.

**Comment by EricKuck** [comment]
I appreciate the bug report. Wasn't questioning the validity of using LinkedHashMap, just trying to understand. Thanks!
