### ISSUE TITLE
Support for field naming policies

### ISSUE THREAD

**Issue by pardom** [bluelinelabs/LoganSquare#4]
It would be nice to have support for field naming policies [a la Gson](http://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/FieldNamingPolicy.html) in addition to exclusive field generation (#2).

**Comment by EricKuck** [comment]
Since this library does all its magic at compile-time instead of runtime (like GSON), it could be tricky to get a field naming policy in there. It might have to be a per-object parameter (ie @JsonObject(namingPolicy = CAMEL_CASE). 

Any thoughts on that? Could be annoying to have to do that on every model class, but I can't think of a better way off the top of my head. 

I'd like to hear some other opinions and get a feel for how desired something like this would be.

**Comment by pardom** [comment]
I think this would be a good solution when used in conjunction with #2. Even if #2 isn't implemented, it would still cut out boilerplate. 1 vs n annotation values.

**Comment by EricKuck** [comment]
This hasn't been documented or released to JCenter yet, but commit 41572aa599ec6deba268b3fa3928c1453d7c3b73 adds two new optional parameters to `@JsonObject`. 

The first is `fieldDetectionPolicy`, which takes an enum with options for `ANNOTATIONS_ONLY`, `NONPRIVATE_FIELDS`, and `NONPRIVATE_FIELDS_AND_ACCESSORS`. The ANNOTATIONS_ONLY options is the default, which is to only parse and serialize fields that have been annotated as `@JsonField`s. The `NONPRIVATE_FIELDS` option will parse and serialize all public or package-local fields, unless they've been annotated with `@JsonIgnore`. The `NONPRIVATE_FIELDS_AND_ACCESSORS` will parse and serialize all the same fields as `NONPRIVATE_FIELDS`, plus any fields that have public or package-local getters and setters.

The second field is `fieldNamingPolicy`, which handles how fields are expected to be named in the JSON. This is also an enum, with options for `FIELD_NAME` and `LOWER_CASE_WITH_UNDERSCORES`. The `FIELD_NAME` options is the default, and it will assume that your JSON has the same field names as your Java variables, unless they're annotated with `@JsonObject(name = "...")`. The `LOWER_CASE_WITH_UNDERSCORES` option will assume that your JSON has the same field names as your java variables, except in lower case with underscore format (again, unless annotated with `@JsonObject(name = "...")`.

How do these changes look? Are there any other field naming policies that might be useful? 

If you'd like to get this running before it's on JCenter, run `./gradlew publishToMavenLocal` on the root of the library source to get it in your local Maven repo. After that, you can use it in your own apps by changing the 1.0.1 versions to 1.0.2 on both the compiler and the runtime dependencies in your build.gradle file.

**Comment by EricKuck** [comment]
The library's been updated on JCenter. It's now 1.0.3 and includes the changes mentioned above. Hope that satisfies everyone's needs. Documentation will be added to the README.md file later tonight.
