### ISSUE TITLE
Re: Not an issue, but a question.

### ISSUE THREAD

**Issue by amalChandran** [bluelinelabs/LoganSquare#40]
How did you guys get the benchmarks from. Can you please tell the way to get the benchmarks so that, we can demo it to our leads and use LoganSquare in our apps. :)

**Comment by EricKuck** [comment]
There's a BenchMark demo included in the repo that you can put on whatever phones you'd like to test it on. Note that the 400% improved performance metric was found using Android 5.0. It seems to be more like 150-200% with previous versions (due to ART vs. Dalvik).
