### ISSUE TITLE
Has IgnoreUnknown feature?

### ISSUE THREAD

**Issue by yongjhih** [bluelinelabs/LoganSquare#45]
It's great project.
I saw @JsonIgnore but ignoreUnkown. Do you have ignoreUnknown plan?

**Comment by EricKuck** [comment]
And what would ignoreUnknown do exactly? What new functionality are you
looking for?

>

**Comment by yongjhih** [comment]
In Jackson, @JsonIgnoreProperties(ignoreUnknown = true) avoid throws exception if against unknown json property.

I think LoganSquare has no this issue.
