### ISSUE TITLE
Any way to support non named JSON Arrays ?

### ISSUE THREAD

**Issue by adnan-SM** [bluelinelabs/LoganSquare#47]
I know this may be far fetched, but I was wondering if there is any way Logan Square could support parsing JSON Arrays without a key. 

Ex : Consider the JSON response from Dribbble below -

[
    {
        "id": 471756,
        "title": "Sasquatch",
        "description": "<p>Quick, messy, five minute sketch of something that might become a fictional something.</p>",
        "width": 400,
        "height": 300,
    }
]

The response can be found documented here - http://developer.dribbble.com/v1/shots/#list-shots

So now, is there any way we could parse the outer array which doesn't have a key ?

**Comment by EricKuck** [comment]
This is already supported using `LoganSquare.parseList()`. Just pass that your InputStream or String and you'll get what you're looking for.
