### ISSUE TITLE
Retrofit converter

### ISSUE THREAD

**Issue by pardom** [bluelinelabs/LoganSquare#5]
It would be nice to have a canonical converter for Retrofit.

https://github.com/square/retrofit/tree/master/retrofit-converters/

**Comment by EricKuck** [comment]
It's on the roadmap! Coming soon.

**Comment by aurae** [comment]
Here's one I threw together earlier:
https://gist.github.com/aurae/8427b93b27483763d9cb

**Comment by EricKuck** [comment]
Awesome, thanks for getting this out there so fast @aurae! We'll be publishing ours a bit later tonight. I'm sure it'll be no better than yours in any way, but we''ll add some unit tests so Square will (hopefully) accept it to their converters repo.

**Comment by EricKuck** [comment]
Given that Retrofit is in the process of changing how their converters work (the interface that's on master now is different from the interface that the rest of the 3rd party converters use), I'm going to put off writing an "official" converter for LoganSquare for the time being. Once their code changes are complete I'll publish a converter. 

Until then, @aurae's implementation looks pretty good. The only change I'd recommend making is to check for an empty list in the toBody method.

**Comment by dsdebastiani** [comment]
I'm using @aurae implementation of converter, but I think that isn't converting Date types.

In my model I have:
```
@JsonObject
public class MyModel {
    @JsonField(name = "ExpireDate", typeConverter = MyDateTypeConverter.class)
    public Date expireDate;
}
```
And my converter:
```
public class MyDateTypeConverter extends DateTypeConverter {
  private DateFormat mDateFormat;

  public MyDateTypeConverter(){
    mDateFormat = new SimpleDateFormat("yyy-MM-dd'T'HH:mm:ss.SSSZ");
  }

    @Override
    public DateFormat getDateFormat() {
        return mDateFormat;
    }

}
```

When Gradle try to compile the project, it trows an error:
```
Error:typeConverter elements must implement the TypeConverter interface or extend from one of the convenience helpers (ie StringBasedTypeConverter or DateTypeConverter).
Error:Exception while processing Json classes. Stack trace incoming:
  java.lang.NullPointerException
  	at com.bluelinelabs.logansquare.processor.ObjectMapperInjector.getParseFieldIfStatement(ObjectMapperInjector.java:205)
```

**Comment by EricKuck** [comment]
@dsdebastiani Sorry about that! Looks like it's actually a bug in LoganSquare, not @aurae's implementation. It's been fixed in the development branch. I'll try to get a new build out on JCenter and Maven Central before the end of the day. I have a bunch of changes on dev that I want to get some much better tests around before pushing it live.

**Comment by EricKuck** [comment]
@dsdebastiani The fix is now live in version 1.0.6.

**Comment by felipeska** [comment]
yay! :metal:

**Comment by ch8908** [comment]
I'm using @aurae 's implementation, but when I return `Observable<Void>` as a request result, it shows error:
```
com.bluelinelabs.logansquare.NoSuchMapperException: Class java.lang.Void could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
```
Can I return a `Void` type in Observable?

**Comment by aurae** [comment]
Version 1.0.0 of my LoganSquare converter has been released [and added to the Retrofit wiki](https://github.com/square/retrofit/wiki/Converters)!

**Comment by EricKuck** [comment]
Thanks @aurae!
