### ISSUE TITLE
NoSuchMapperException

### ISSUE THREAD

**Issue by pavanjaju** [bluelinelabs/LoganSquare#53]
Hi,

I am trying to serialize a collection to json, but while doing that getting following exception
>"Class java.util.ArrayList could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?"

Code at which I am getting this error
>Realm realm = Realm.getInstance(this);
>                List<UncaughtException> uncaughtExceptions = new ArrayList<>(realm.allObjects(UncaughtException.class));
>                try {
>                    String json = LoganSquare.serialize(uncaughtExceptions);
>                    Toast.makeText(this, json, Toast.LENGTH_LONG).show();
>                } catch (IOException e) {
>                    e.printStackTrace();
>                }

Please do correct me if i am missing something or doing something wrong. New to LoganSquare :)

**Comment by EricKuck** [comment]
The correct method to use for this would be: `serialize(List<E> list, Class<E> jsonObjectClass)`. Even if you used this though, is the `UncaughtException` class annotated as an `@JsonObject`?
