### ISSUE TITLE
How to import values from a JSON array when you don't know the keys yet?

### ISSUE THREAD

**Issue by falcon4ever** [bluelinelabs/LoganSquare#57]
Does LoganSquare support importing values from JSON arrays when it's not know what they might be?

For example, for a project I retrieve a JSON that might be filled with certain properties that can change over time as some properties rely on an external source. However, I would like to be able to access/store all of these values.

// Example one, current situation a "query" array has 3 key->value pairs all strings.
```
"query": {
        "param1": "blablabla",
		"param2": "blablabla",
		"code": "1244"
}
```
	
// Example two, new situation, param2 is no longer used, a new key "useKey" with a boolean value has been added.
```
"query": {
        "param1": "blablabla",
		"code": "1244"
		"useKey": false
}	
```
		
I was hoping to do something like this? But I don't know how else I can store a mixed Key->Value array using LoganSquare.
Java:
```
@JsonObject
public class GameModel {
    @JsonField
    private HashMap<String, Object> query;
}
```
Any tips on how to solve this problem?

**Comment by EricKuck** [comment]
If you don't know what the keys are, how will you use it in your app? Things like this can't really be represented with a POJO, which is a problem you'll have with any JSON library you use.

If it's just a matter of one or two keys switching off (maybe "param2" is there sometimes and "useKey" is there others), just include both in the model. If the keys are truly unknown, you'll have to use a Map. No way around it, no matter how you parse the data.

**Comment by falcon4ever** [comment]
Hi Eric,

thanks for your reply. 

Maybe I should clarify that in my project I'm using data that comes back from the server to construct custom POST/GET requests to reach web pages. Our API returns all the parameters that are required (i.e. url + POST/GET values) to make a successful call (the query part). For every website the query part will be different and only needed be for the request, there is no need to store the values and display them in the app.

Before LoganSquare I was using the inbuilt JSONObject and JSONArray to walk through the entire JSON result and for certain elements I would just store it in a JSONObject. I'd prefer to use LoganSquare though as it's way faster to process the JSON result.

Since you're suggesting I should be using a Map to map the unknowns (query part). How would I do that?

I tried this:
```
@JsonObject
public class WebModel {

	@JsonField
    private String url;
	
	@JsonField
    private String type;	// POST or GET
	
    @JsonField
    private Map<String, Object> query;
}
```

But that will result in:
```
Class java.lang.Object does not having a TypeConverter defined. TypeConverters can be added using LoganSquare.registerTypeConverter()
```

It seems like I can't just make the value part of the Map an Object object and deal with the casting later. Like in my previous post, the query part can be anything (e.g. String, boolean, number)
