### ISSUE TITLE
Could not be mapped to a JSONObject Exception

### ISSUE THREAD

**Issue by adnan-SM** [bluelinelabs/LoganSquare#58]
I get the following error when trying to parse an object to JSON 

```
com.bluelinelabs.logansquare.NoSuchMapperException: Class io.realm.ShotRealmProxy could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
            at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:171)
            at com.bluelinelabs.logansquare.LoganSquare.serialize(LoganSquare.java:100)
```
I use Realm as the underlying database and the object I am trying to parse is a model class which extends RealmObject class. The model class has been annotated with @JsonObject but looking at the error I think its trying to convert the Base class which in my case is the generated class by Realm. Any ideas as to what can be done ?

**Comment by EricKuck** [comment]
If you want to share some code I'd be happy to look, but I'm 99% sure your issue is just that the object you're trying to serialize is of the io.realm.ShotRealmProxy type rather than your subclass. Super easy way to tell: just log the result of myObject.getClass() right before you try to serialize it.

**Comment by adnan-SM** [comment]
Here is the piece of code causing the crash : 

```
 @Override
    public void onShotItemClicked(View view, Shot shotTest) 

        if (shotTest == null) {

            Log.e(LOG_TAG, "Whoa shot is null");
        }else {

            Log.e(LOG_TAG, " shot is not null, image found : "+shotTest.getImages().getNormal());
        }

        try {
            jsonString = LoganSquare.serialize(shotTest);
        } catch (IOException e) {
            e.printStackTrace();
        }
```

ShotTest is an object fetched from Realm DB & passed to the onClick Handler.

**Comment by EricKuck** [comment]
If the object is a ShotRealmProxy and not annotated as a `@JsonObject`, it's not going to work. So I guess I'm not sure what kind of answer you're looking for?

**Comment by ntimesc** [comment]
i am facing the same issue following is my code AppointmentRealmProxy is autogenerated code ( so i cant alter it )by realm , i have written the serialize converter but still facing the same issue.

 RealmResults<Appointment> appointments = DB.getInstance(mContext).selectNotSyncAppointmentsData();

```
    Appointment data = appointments.get(0);
        // send to server
    RestApi.AppointmentsDataApi service = getAppointmentsDataApi();


    Call<APResponse> call = service.createUpdateAppointmentsData(data);
```

**Comment by peterbetos** [comment]
Here's the issue I logged for Realm:

https://github.com/realm/realm-java/issues/3235
