### ISSUE TITLE
[Question] When @JsonIgnore with optional parse/serialization policies will get into public release?

### ISSUE THREAD

**Issue by igokoro** [bluelinelabs/LoganSquare#59]
I've tried to use LoganSquare - and it seems to meet all my needs except one for now: I need to always parse all fields but serialize only some of them. I've seen code for this is already implemented in the development branch.

Are there any plans to merge it into master? If so when can we expect public release of this functionality?

**Comment by EricKuck** [comment]
Sorry about the long wait! Stuff has been crazy lately. I finally got back to working on this library today and hope to have all the new stuff merged in over the weekend. I'll let you know.

**Comment by EricKuck** [comment]
This has now been pushed to master in 7d6f2e6f6c0bd10e31b3fa9fce112e8cb0fb252c and is available on JCenter as version 1.1.0.
