### ISSUE TITLE
Allow private fields

### ISSUE THREAD

**Issue by pardom** [bluelinelabs/LoganSquare#6]
It would be nice to provide encapsulation for @JsonField class members.

I've been struggling with the proper way to implement this same issue in [Ollie](https://github.com/pardom/Ollie/pull/15), and I think an ideal solution would be for the processor to require get/set methods corresponding to private fields using naming conventions.

Thoughts?

**Comment by EricKuck** [comment]
That's actually exactly how it works already. If a field is private, it'll use your accessor methods.

**Comment by pardom** [comment]
:smile: Awesome! Didn't catch that.

**Comment by EricKuck** [comment]
I didn't exactly document that aspect of it, so no worries! Still trying to figure out how to manage documenting all the little aspects of a project like this without throwing an overwhelming amount of stuff on the README.md file.

**Comment by pardom** [comment]
Yeah, no worries. I'm terrible at documentation. For [ActiveAndroid](https://github.com/pardom/ActiveAndroid/#documentation) I opened the wiki for contribution and let the community help with docs.

**Comment by EricKuck** [comment]
Genius! I'll do something like that soon.

**Comment by talklittle** [comment]
Private fields still not supported for custom classes.

Example generated code:

    public static void _serialize(ButcherShop object, JsonGenerator jsonGenerator, boolean writeStartAndEnd) throws IOException {
      if (writeStartAndEnd) {
        jsonGenerator.writeStartObject();
      }
      jsonGenerator.writeNumberField("total", object.getTotal());
      if (object.meats != null) {                 // ********DOES NOT COMPILE
        jsonGenerator.writeFieldName("meats");
        LoganSquare.typeConverterFor(Meat[].class).serialize(object.getMeats(), "meats", jsonGenerator);
      }
      if (writeStartAndEnd) {
        jsonGenerator.writeEndObject();
      }
    }

With JSON model class:

    public class ButcherShop {
        private long total;
        private Meat[] meats;

        public long getTotal() {
            return total;
        }

        public void setTotal(long total) {
            this.total = total;
        }

        public Meat[] getMeats() {
            return meats;
        }

        public void setMeats(Meat[] meats) {
            this.meats = meats;
        }
    }

Simple workaround on app developer's side: change `meats` visibility to package-private by removing `private` keyword. Thankfully the generated `ButcherShop$$JsonObjectMapper` class is in the same package as the original class.

**Comment by EricKuck** [comment]
Nice catch @talklittle. I'll reopen this issue and push a fix soon.

**Comment by EricKuck** [comment]
@talklittle This has been fixed in commit dae0d5e407b665d66142783d58270f5c824ea5ba and will be released to gradle as version 1.0.2 within the next day or two.

**Comment by talklittle** [comment]
Awesome, thanks! That commit does fix the behavior for primitives and general custom classes.

However, I found another broken case, `private java.util.Map<String, Object>` still generates broken code. Guess it is a separate deserialization case.
