### ISSUE TITLE
JsonNode

### ISSUE THREAD

**Issue by ppamorim** [bluelinelabs/LoganSquare#61]
LoganSquare has a similar class JsonNode of Jackson?

**Comment by EricKuck** [comment]
No, it doesn't. What would you use it for?

**Comment by ppamorim** [comment]
I've a modular models on my server. I need use this workaround to work well.

**Comment by EricKuck** [comment]
Sorry, the point of this library is to get your JSON to a Java object. It's
not going to support anything like JsonNode.

**Comment by EricKuck** [comment]
It's not quite the same, but parsing to a Map seems like it might do what you want, right?

**Comment by ppamorim** [comment]
Yes
