### ISSUE TITLE
Allow user to register custom JsonMapper.

### ISSUE THREAD

**Issue by mariotaku** [bluelinelabs/LoganSquare#63]
This would be useful if you want to abstract model with interface.

Like

````java
public static <E> void registerJsonMapper(Class<E> cls, JsonMapper<E> mapper) {
    OBJECT_MAPPERS.put(cls, mapper);
}
````

**Comment by EricKuck** [comment]
I'm not opposed to this, but what's the use case? What can you do with this
that you can't do with annotations and/or TypeConverters?

**Comment by mariotaku** [comment]
For example, Twitter's IDs API could return both formats:
````json
[1, 2, 3, 4]
````
````json
{
  "ids": [
    1, 2, 3, 4
  ]
}
````
I'd rather write JsonMapper by myself, because split above results to two model class is inconvenient.

**Comment by rey5137** [comment]
+1. I tried to serialize a String[] but it gave me this error:
```
com.bluelinelabs.logansquare.NoSuchMapperException: Class java.lang.String[] could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
```

So for now, I have to copy all the code from `LoganSquare` class and add a method `registerMapper`.

**Comment by mariotaku** [comment]
Hi, @EricKuck , do you have any idea about this request?

**Comment by EricKuck** [comment]
@rey5137's use case is now handled in the latest version. I honestly can't think of a good way to allow users to add `JsonMapper`s, as that's meant to be an internal class which is subject to change. Which endpoints of the Twitter API could return different formats? I couldn't find anything like that looking through their docs.

**Comment by mariotaku** [comment]
@EricKuck Thanks for update.

My use case is a little bit odd... My model classes are all interfaces, and their implementations are annotated with JsonObject. So I register those interface classes to OBJECT_MAPPERS.

As for use of internal JsonMapper, I can give you an example.
Here I have a class called IDs.
````java
class IDs {
    long[] ids;
    long previousCursor;
    long nextCursor;
}
````

Server returns these for IDs:

```json
[ 1, 2, 3, 4 ]
````

````json
{ "ids" : [ 1, 2, 3, 4 ] , "previous_cursor": 1 , "next_cursor": 1}
````

So I have to write JsonMapper on my own.

Is it possible to make those private fields like OBJECT_MAPPERS package private? So I can use some internal APIs in this library without using reflection.

**Comment by mariotaku** [comment]
Also, twitter has an undocumented api, which returns format like this:
````json
{
  "action": "[a string object]",
  "sources": [{
    "type": "value"
  }],
  "targets": [{
    "type": "[could be three different types]"
  }],
  "target_objects": [{
    "type": "[could be three different types]"
  }]
}
````
I have to return different object depending on "action", so it's needed to implement my own JsonMapper.

**Comment by EricKuck** [comment]
I'd probably still recommend against doing this, but it is now supported. There's no register functionality, but just end your class name with $$JsonObjectMapper and you should be good to go. Keep in mind the interface for object mappers is subject to change, since it's designed to be an internal class. If you go this route you may end up having to re-write a bunch of your code when LoganSquare updates.
