### ISSUE TITLE
Supporting the Jaxb Annotation.

### ISSUE THREAD

**Issue by gencube** [bluelinelabs/LoganSquare#67]
Hi,

Since many DTO(Data Transfer Objects) and for some other code Models has already been annotated with the OLD but working annotation, JAXB. And also they are part of the JEE 
standard anyway. Please consider supporting them and reuse their code.

http://www.vogella.com/tutorials/JAXB/article.html

```java
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "book")
// If you want you can define the order in which the fields are written
// Optional
@XmlType(propOrder = { "author", "name", "publisher", "isbn" })
public class Book {

  private String name;
  private String author;
  private String publisher;
  private String isbn;

  // If you like the variable name, e.g. "name", you can easily change this
  // name for your XML-Output:
  @XmlElement(name = "title")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public String getPublisher() {
    return publisher;
  }

  public void setPublisher(String publisher) {
    this.publisher = publisher;
  }

  public String getIsbn() {
    return isbn;
  }

  public void setIsbn(String isbn) {
    this.isbn = isbn;
  }

} 
```

It will make your library even easier to be adopted by other enterprises.

**Gson and Jackson both uses such object transparently.**

**Comment by EricKuck** [comment]
As I said in https://github.com/bluelinelabs/LoganSquare/issues/39, 

>Those annotations don't really cover all of the use cases of this library, and definitely wouldn't cover future use-cases. Trying to use anyone else's annotations would really cripple our ability to add anything new. What would the benefit of supporting for these be, besides saving developers ~2 minutes of annotating their models?
