### ISSUE TITLE
Custom parser

### ISSUE THREAD

**Issue by stephanenicolas** [bluelinelabs/LoganSquare#69]
Hi,

we would like to give LoganSquare a go. But we have actually one case that we don't think can be handled by LoganSquare directly, and we would love to be wrong ;) : 
we have some lists of objects received from JSON, these items are too big to all fit into memory. With Jackson, we currently use a simple module and a custom deserializer to save each entry in a database directly, and the deserializer itself returns null. This saves a great amount of memory. 

Would it be possible to do the equivalent with Logan Square ?

Thanks for your lib, it's breeze in parsing world.

**Comment by EricKuck** [comment]
Going through and trying to clean up some of the older issues and came across this one again. Unfortunately this isn't (and probably never will be) supported, so it would require rewriting very significant amounts of the library.
