### ISSUE TITLE
Comparison to ig-json-parser?

### ISSUE THREAD

**Issue by eveliotc** [bluelinelabs/LoganSquare#7]
I see you guys are comparing it to GSON and Jackson, but have you thought in comparing it with another Jackson based code generation thingy like ig-json-parser?

**Comment by EricKuck** [comment]
Since they work the same way and generate very similar code, I'm sure performance will be more or less identical to ig-json-parser. Considering that ig-json-parser has been abandoned and doesn't really do half the stuff this library does, it doesn't seem worth the comparison.
