### ISSUE TITLE
Test class conversion support

### ISSUE THREAD

**Issue by LouisCAD** [bluelinelabs/LoganSquare#70]
Hi!
I am building a connected app with REST. I use Spring framework for android, so I'm building a HttpMessageConverter to convert String from json and to json. But the superclass I'm extending requires me to implement a method to check if my Converter supports a class. Could you add a static method in LoganSquare testing if a class is supported (eg is annotated)?
It may be ```boolean LoganSquare.supports(Class<?> class)```

Regards

**Comment by EricKuck** [comment]
This will be added in the next version.

**Comment by EricKuck** [comment]
This is now in v1.2.5.

**Comment by LouisCAD** [comment]
Yeah! Thank you! I'll add it when I reach office Tuesday!

BTW, I used your library in a Retrofit Project, and built my own converter. Would you like me to give you the code to get more visibility with Square library?

**Comment by EricKuck** [comment]
@aurae actually got his converter added to the official Retrofit wiki recently, but thanks! You can check it out here: https://github.com/square/retrofit/wiki/Converters

**Comment by LouisCAD** [comment]
My implementation is very different from @aurae one! It contains less lines of code, and is still working (although I didn't test for serializing for now). You can check my code [here](https://github.com/LouisCAD/PopularMovies/tree/master/app/src/main/java/xyz/louiscad/popularmovies/rest/converter) in a working project (which needs a TMDb API key)

**Comment by aurae** [comment]
6 of the 7 tests I have implemented for the Retrofit converter fail with your implementation. I was baffled at how many classes I needed to handle `Map`s, `List`s etc. as well, but it is still the minimum implementation required for Retrofit 2's architecture.

**Comment by LouisCAD** [comment]
@aurae So, why my implementation is working in my case, but not in your tests? It's because of Lists and Maps, or is there other cases in which my implementation isn't working? Do you have the tests results so I can understand what fails?

**Comment by aurae** [comment]
It's mostly because of Lists and Maps, yes. You can find the test suite [here](https://github.com/aurae/retrofit-logansquare/tree/master/converter-logansquare/src/test/java/com/github/aurae/retrofit). The main point is: Don't assume that every `Type` is also a `Class<?>` in your Converters!

**Comment by LouisCAD** [comment]
@aurae Yeah! It's much easier to understand your library now! Happy to see I helped!
