### ISSUE TITLE
Can't serialize List<String>

### ISSUE THREAD

**Issue by ch8908** [bluelinelabs/LoganSquare#73]
Ex:
```
List<String> ids = new ArrayList<>();
ids.add("493d859e-a2cd-4da5-ba35-3f1dca665d03");
ids.add("483cea23-6f11-486e-8975-79c29b5ea9e4");
String serialize = LoganSquare.serialize(ids);
```
It shows error:
```
Class java.lang.String could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
```
But String is Build-in support type, how can I serialize a List of string?

**Comment by burntcookie90** [comment]
@ch8908 I don't know if logan square supports runtime deserialization like this, at least, not that I could figure out. Since I'm using retrofit, I just use gson for the runtime stuff that might not have the annotations, but I don't prefer it.

**Comment by EricKuck** [comment]
@ch8908 @burntcookie90 It does not currently support this, but I'm working on adding support for it. Should be available in a few days.

**Comment by burntcookie90** [comment]
Nice, how are you including support for it?

**Comment by EricKuck** [comment]
Sorry about the long wait, but this should now work great.
