### ISSUE TITLE
com.bluelinelabs.logansquare.NoSuchMapperException

### ISSUE THREAD

**Issue by indusamobility** [bluelinelabs/LoganSquare#74]
I have tried importing the project in eclipse and have added following jar files 

logansquare-compiler-1.1.0
logansquare-1.1.0
jackson-core-2.5.0

import java.util.List;

import com.bluelinelabs.logansquare.annotation.JsonField;
import com.bluelinelabs.logansquare.annotation.JsonObject;

here is my model 

@JsonObject
public class Image {

    /*
     * Standard field declaration.
     */
    @JsonField
    public String format;

}

here is now i serialize it

Image val = new Image();
		val.format="mydata";
		
		try {
			String data = LoganSquare.serialize(val);
			
			Log.e("addData ", data);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

but i am getting following error 

07-17 08:16:30.854: E/AndroidRuntime(17857): Process: com.demo.fsa, PID: 17857
07-17 08:16:30.854: E/AndroidRuntime(17857): com.bluelinelabs.logansquare.NoSuchMapperException: Class com.demo.model.Image could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:172)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at com.bluelinelabs.logansquare.LoganSquare.serialize(LoganSquare.java:101)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at com.demo.fragments.SignInFragment.addData(SignInFragment.java:104)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at com.demo.fragments.SignInFragment.onCreateView(SignInFragment.java:93)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.View.measure(View.java:16497)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1052)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.View.measure(View.java:16497)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.View.measure(View.java:16497)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1052)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.View.measure(View.java:16497)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.View.measure(View.java:16497)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.View.measure(View.java:16497)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.View.measure(View.java:16497)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.View.measure(View.java:16497)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1912)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1109)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
07-17 08:16:30.854: E/AndroidRuntime(17857): 	at android.os.Handler.hand

**Comment by EricKuck** [comment]
This library relies on compile-time processing to function. You can't just import the jars and expect it to work. Either maven or gradle are supported.

**Comment by indusamobility** [comment]
can you please tell me what dependency i have to include for maven

**Comment by EricKuck** [comment]
I've never really used maven for Android, since gradle has been the officially supported build method for over a year now, but I think you'll be able to build if you add these two:

'com.bluelinelabs:logansquare-compiler:1.1.0'
'com.bluelinelabs:logansquare:1.1.0'

**Comment by indusamobility** [comment]
i tried added these three but no luck :( 

	  	<dependency>
	<groupId>com.bluelinelabs</groupId>
	<artifactId>logansquare-compiler</artifactId>
	<version>1.1.0</version>
</dependency>

  <dependency>
	<groupId>com.squareup</groupId>
	<artifactId>javapoet</artifactId>
	<version>1.2.0</version>
</dependency>

    <dependency>
	<groupId>com.bluelinelabs</groupId>
	<artifactId>logansquare</artifactId>
	<version>1.1.0</version>
</dependency>
