### ISSUE TITLE
can this lib support generics serialization and deserialization?

### ISSUE THREAD

**Issue by hamberluo** [bluelinelabs/LoganSquare#78]
- i found that only jackson can do this properly.
- but jackson has too many code methods.

**Comment by EricKuck** [comment]
This will be in the next update.

**Comment by EricKuck** [comment]
This is now supported in the latest version. Instead of using LoganSquare.parse(is, YourModel.class), use this: LoganSquare.parse(is, new ParameterizedType<YourModel<DataModel>>() { }).
