### ISSUE TITLE
Duplicate CONVERTER fields

### ISSUE THREAD

**Issue by mariotaku** [bluelinelabs/LoganSquare#79]
I have two ObjectConverter class, which called TimelineType.Converter and TweetType.Converter, LoganSquare generates two CONVERTER fields.

````
protected static final TimelineType.Converter CONVERTER = new TimelineType.Converter();

protected static final TweetType.Converter CONVERTER = new TweetType.Converter();
````

I think LoganSquare could add number suffix to converter field, or use name like TIMELINETYPE$CONVERTER .

**Comment by EricKuck** [comment]
Good catch. Will be fixed in the next version.

**Comment by EricKuck** [comment]
This is fixed (finally) in v.1.2.4.
