### ISSUE TITLE
Jackson annotations?

### ISSUE THREAD

**Issue by eveliotc** [bluelinelabs/LoganSquare#8]
Hello,

Wondering why you decided to go with own annotations over say `JsonProperty` and friends from https://github.com/FasterXML/jackson-annotations

**Comment by EricKuck** [comment]
Jackson's annotations don't handle everything we needed for this library, so we couldn't really just reuse them. They're also all declared as runtime annotations, which adds (a tiny bit of) bloat to your final APK.
