### ISSUE TITLE
Could anyone please make a performance competition against fastjson ?

### ISSUE THREAD

**Issue by liushuaikobe** [bluelinelabs/LoganSquare#82]
https://github.com/alibaba/fastjson .

[There's](https://github.com/eishay/jvm-serializers/wiki) its benchmark data.

**Comment by EricKuck** [comment]
With a jar of almost half a meg, fastjson doesn't really seem like a good
choice for Android apps. Pull requests are welcome though. Shouldn't take
you longer than 15 minutes.
