### ISSUE TITLE
Ignore setters and getters for public fields

### ISSUE THREAD

**Issue by AndreasBackx** [bluelinelabs/LoganSquare#86]
Is it possible to ignore setters and getters for public fields? Currently when you have private setters and getters it still tries to use those instead of using the public field directly.

**Comment by aurae** [comment]
I'm not sure why you would even need `private` accessors and mutators for `public` fields?

**Comment by AndreasBackx** [comment]
I was giving a `private` setter and getter as an example. The same would apply for `public` getters and setters for a public field. Is it possible to ignore those?

**Comment by EricKuck** [comment]
It's not possible to ignore these with the current library, but I'd be open to suggestions on how that should be implemented. Like @aurae though, I'm not really sure why you'd want to do that.

**Comment by ellsworthrw** [comment]
I am porting my code to LoganSquare and have this problem. I have a field that is an implementation detail that I do not want exposed outside of the class. The only way around this problem is to remove the getter and make the class access the field directly.
