### ISSUE TITLE
How can I use this lib in eclipse?

### ISSUE THREAD

**Issue by MostafaSh** [bluelinelabs/LoganSquare#91]
How can i use this lib in eclipse? is it possible?

**Comment by aurae** [comment]
You probably can, using [Eclipse's APT support](https://www.eclipse.org/jdt/apt/introToAPT.php).

**Comment by LouisCAD** [comment]
@MostafaSh You should use Android Studio, or IntelliJ if not developing for Android. If you build for Android, Eclipse support has been dropped…

**Comment by EricKuck** [comment]
Like @aurae said, you can probably use Eclipse's APT support, but like @LouisCAD said....why?
