### ISSUE TITLE
Lib is much slower than manual parsing of JSONObject

### ISSUE THREAD

**Issue by MGasztold** [bluelinelabs/LoganSquare#94]
Today I have tried to use LoganSquare to speed up parsing of my JSON which is pretty huge (contains a long arrays and its overall size is over 1 MB). 

I serialized my class to which I load the data from the JSON (i added @JsonObject, @JsonField annotations to the fields etc.). Eventually I used HttpUrlConnection to download the InputStream object that i put straight to the LoganSquare.parse(...) method.

In general the data is successfully loaded into my object and the thing is working but as I compared the timings i got the following:
 - my own straightforward, no serialized parsing of the JSONObject response from volley request using JSONReader (http://developer.android.com/reference/android/util/JsonReader.html) - > 15 seconds
 - LoganSquare: 45 seconds.

Do you think i might be doing something wrong? Any help/hint would be appreciated.

**Comment by EricKuck** [comment]
Sounds like you're definitely doing something wrong if this is slower than JsonReader (which is really slow). Do you have a sample project we could try out?

**Comment by MGasztold** [comment]
I have found another reason of my problems. Your library works totally fine and is a bit faster than JSONReader.
